install:
 - mvn -B clean; java -version
script:
 - travis_wait 60 mvn -B -Ptravis,jboss-repository -fae -Dserver.version=$SERVER_VERSION ${ELYTRON:+-Delytron} install -Dtest=SseAPITest

language: java
jdk:
  - openjdk8
env:
  - SERVER_VERSION=18.0.1.Final
jobs:
  exclude:
    - jdk: openjdk11
      env: SERVER_VERSION=19.0.0.Final ELYTRON=true
  include:
    - stage: "javadoc"
      script: mvn -B -Pjboss-repository -DskipTests install && mvn -B -Dmaven.javadoc.skip=false javadoc:javadoc
      jdk: openjdk8
      env: SERVER_VERSION=19.0.0.Final
    - stage: "javadoc"
      script: mvn -B -Pjboss-repository -DskipTests install && mvn -B -Dmaven.javadoc.skip=false javadoc:javadoc
      jdk: openjdk11
      env: SERVER_VERSION=19.0.0.Final
addons:
  hosts:
    - localhost.localdomain
##cache:
# directories:
#  - $HOME/.m2
