script:
 -  mvn -B -Ptravis,jboss-repository -fae -Dserver.version=$SERVER_VERSION ${ELYTRON:+-Delytron} install

language: java
jdk:
  - openjdk8
env:
  - SERVER_VERSION=19.0.0.Final
addons:
  hosts:
    - localhost.localdomain
cache:
 directories:
  - $HOME/.m2
