install:
 - mvn -B clean; java -version
script:
 - travis_wait 60 mvn -B -Ptravis,jboss-repository -fae -Dserver.version=$SERVER_VERSION ${ELYTRON:+-Delytron} install

language: java
jdk:
  - openjdk8
  - openjdk11
env:
  - SERVER_VERSION=18.0.1.Final
  - SERVER_VERSION=19.0.0.Final
addons:
  hosts:
    - localhost.localdomain
##cache:
# directories:
#  - $HOME/.m2
